site_name: Sanp's Blog
site_author: Steve SanPietro
site_description: A blog about tech and programming
site_url: https://sanp.github.io
remote_branch: master
remote_name: origin
copyright: "Copyright © 2019 Steve SanPietro"
theme:
  name: 'material'
  custom_dir: 'theme'
extra_css:
  - 'style/css/extra.css'
extra_javascript:
  - 'style/js/extra.js'
plugins:
  - search
  - macros
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - markdown.extensions.attr_list
extra:
  github:
    page: https://github.com/sanp
    repos:
      dotfiles: dotfiles
  posts:
    gitflow:
      part1_title: &gitflow_part1_title 'Gitflow Part 1: Overview of Gitflow'
      part2_title: &gitflow_part2_title 'Gitflow Part 2: Step by step guide to Working on a feature'
    
nav:
  - Home: index.md
  - About: about.md
  - 2019: 
    - 'Using interactive rebase to ensure a clean git history': '2019/rebasing.md'
    - *gitflow_part1_title: '2019/gitflow_1.md'
    - *gitflow_part2_title: '2019/gitflow_2.md'
