site_name: Sanp's Blog
site_author: Steve SanPietro
site_description: A blog about tech and programming
remote_branch: master
remote_name: origin
copyright: "Copyright © 2019 Steve SanPietro"
theme:
  name: 'material'
  custom_dir: 'theme'
plugins:
  - search
  - macros
nav:
  - Home: index.md
  - About: about.md
  - Posts: posts.md
extra:
  github:
    page: https://github.com/sanp
    repos:
      dotfiles: dotfiles
